security:
    password_hashers:
        App\Entity\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppAuthenticator
            logout:
                path: app_logout
                target: app_homepage
    access_control:
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/cart, roles: ROLE_USER }
        - { path: ^/models/, roles: PUBLIC_ACCESS }